travis:
  secure:
    BINSTAR_TOKEN: TN+1KpDDVbZxQ3Ya0XMbHiQFWEmE5KkA1/u1a+X4WKfLAsZCquwZzHqGQYVNuaiWWhA0N2kAFYtsfAHdL2aga3sVH/SKgibCY8RZZ2GF+DDXAY2MuThpOKONt4NrqU7LfNnow4/OjCMVc906vSrhkJdSDwbVxBZ7JDEn+L+6KaUY2TiSk3qtwXaK++JzBTVirX6sp43qAx6BSoBfuE+LMJUi8fLEf1vabd96WvD7/iAncYsonHMsZuMGPmUe56UE3Ve7OPdqBjFUdUje31oxTbnnb1aCQu/DnyiIZbkVZHHkuIqTfYA5CAfNAAA3RatYx1xziTghoxxWPU//UsGE5VUVFG3D8WgO0kbRaHmsZSgYBkVOPMc/oXz3vX3m8B1k9Ceu9I55pFS2OwRwD9bJC+YjJB3Jvs6PyKEC+CrkRK4wFLXvnR5NH2KxvqAtEO8LZJzTT1RIt+1PulnIuyzINL4rGv89F7Zm99ZQVGHgUoVEoc1yGIw9V20iyqlpCnj92gs1YG9I7J2tBS5Mg903yX/7DbvYRMw7zWQVMh+gBKzCZw9+11jB9nGnf0bUaII66yaiVxPnsQ7AU8qnHYgAcZ36smJKwng7Iks5rtoUXB92Qz91yPTF86ch7CkhkDop50XwwO6cx/zQpZK4mIz3HwNZ+JyZx0R6ll5kNLY2xzo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
